# Generated by Django 3.2.6 on 2021-08-25 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explore',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Explore',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('esrb', models.CharField(choices=[('1', 'Teen'), ('2', 'Mature'), (
                    '3', 'Adults Only'), ('4', 'Everyone'), ('5', 'N/A')], max_length=30)),
                ('matacritics', models.IntegerField()),
                ('description', models.CharField(max_length=5000)),
                ('best_of_all_time', models.BooleanField(
                    choices=[('1', 'Yes'), ('2', 'No')])),
                ('release_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Games',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Genres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Publishers',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UpComing',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField()),
                ('games', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='app.games')),
            ],
            options={
                'verbose_name_plural': 'Up Coming Games',
                'ordering': ['-release_date'],
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='games',
            name='genres',
            field=models.ManyToManyField(to='app.Genres'),
        ),
        migrations.AddField(
            model_name='games',
            name='publishers',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='app.publishers'),
        ),
        migrations.AddField(
            model_name='games',
            name='tags',
            field=models.ManyToManyField(to='app.Tags'),
        ),
        migrations.AddField(
            model_name='explore',
            name='upcoming',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='app.upcoming'),
        ),
    ]
