# Generated by Django 3.2.6 on 2021-08-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210825_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='best_of_all_time',
            field=models.BooleanField(),
        ),
    ]
