# Generated by Django 3.2.6 on 2021-08-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_games_best_of_all_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.RemoveField(
            model_name='genres',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='created_at',
        ),
    ]
