# Generated by Django 3.2.6 on 2021-08-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210825_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='esrb',
            field=models.CharField(max_length=30),
        ),
    ]
