# Generated by Django 3.2.6 on 2021-08-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_games_esrb'),
    ]

    operations = [
        migrations.AddField(
            model_name='explore',
            name='best_of_all_time',
            field=models.ManyToManyField(to='app.Games'),
        ),
    ]
