# Generated by Django 3.2.6 on 2021-08-31 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_explore_best_of_all_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upcoming',
            options={'ordering': ['release_date'],
                     'verbose_name_plural': 'Up Coming Games'},
        ),
    ]
