# Generated by Django 3.2.6 on 2021-08-31 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210831_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='explore',
            name='best_of_all_time',
            field=models.ManyToManyField(to='app.Games'),
        ),
        migrations.RemoveField(
            model_name='explore',
            name='upcoming',
        ),
        migrations.AddField(
            model_name='explore',
            name='upcoming',
            field=models.ForeignKey(
                default=7, on_delete=django.db.models.deletion.CASCADE, to='app.upcoming'),
            preserve_default=False,
        ),
    ]
