# Generated by Django 3.2.6 on 2021-08-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210831_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explore',
            name='upcoming',
        ),
        migrations.AddField(
            model_name='explore',
            name='upcoming',
            field=models.ManyToManyField(to='app.UpComing'),
        ),
    ]
