# Generated by Django 3.2.6 on 2021-08-31 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210831_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explore',
            name='upcoming',
        ),
        migrations.AddField(
            model_name='explore',
            name='upcoming',
            field=models.ForeignKey(
                default=9, on_delete=django.db.models.deletion.CASCADE, to='app.upcoming'),
            preserve_default=False,
        ),
    ]
