# Generated by Django 3.2.6 on 2021-08-31 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210831_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explore',
            name='best_of_all_time',
        ),
    ]
