# Generated by Django 3.2.6 on 2021-08-31 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_explore_best_of_all_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explore',
            name='best_of_all_time',
        ),
    ]
