# Generated by Django 3.2.6 on 2021-08-31 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_explore_best_of_all_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcoming',
            name='games',
        ),
        migrations.DeleteModel(
            name='Explore',
        ),
        migrations.DeleteModel(
            name='UpComing',
        ),
    ]
